### ISSUE TITLE
Bikeshed 3.11.5 generating multiple copies of `infopanel`s in WebGPU

### ISSUE THREAD

**Issue by kainino0x** [speced/bikeshed#2471]
In Bikeshed 3.11.5 (but not 3.11.4), Bikeshed is generating multiple copies of a few `infopanel`s on the WebGPU spec:

```
WARNING: Multiple elements have the same ID 'infopanel-for-term-for-sec-returnifabrupt-shorthands'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'infopaneltitle-for-term-for-sec-returnifabrupt-shorthands'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'infopanel-for-term-for-map-exists'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'infopaneltitle-for-term-for-map-exists'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'infopanel-for-term-for-ordered-set'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'infopaneltitle-for-term-for-ordered-set'.
Deduping, but this ID may not be stable across revisions.
```

Now, the first two are weird (we create anchors called `?` and `!` pointing to ECMAScript), but removing them doesn't solve it. The others are pretty normal: there are simply 9 references to `[=map/exist=]` and 5 to `[=ordered set=]` which both come from the Infra spec.

Repro:
- Clone https://github.com/gpuweb/gpuweb and cd to `gpuweb/spec/`
- `pip3 install bikeshed==3.11.5 && bikeshed update` (or 3.11.6)
- `bikeshed spec`

**Comment by saschanaz** [comment]
Looks like a regression from #2461.

**Comment by annevk** [comment]
@tabatkins this also impacts Fetch.

**Comment by tabatkins** [comment]
Yeah, this was actually already an issue, I'm just predefining some IDs on those panels now so the ID deduper is *noticing* it.

I'll look into exactly why we're getting dupes today.

**Comment by tabatkins** [comment]
Should be fixed now (at least, Fetch no longer generates any warnings).

I was indeed already generating dupe IDs, but they were of a form that I silently dedup. The recent change added *more* IDs based on those original IDs, that *didn't* trigger the silent deduping, thus the warnings. I've just made the original IDs unique now. (If you can find an MD5 collision you can still trigger the duplicate warning but I'm making that your problem.)

**Comment by saschanaz** [comment]
Thanks, please publish a new release when you get some time.

**Comment by annevk** [comment]
I think in theory api.csswg.org should use the latest Bikeshed though maybe it caches for a while? Or the issue is still present somehow.

**Comment by saschanaz** [comment]
It's just that there's no new release with this fix. (3.11.6 was released before the fix.)

**Comment by tabatkins** [comment]
Yeah, the server tracks pip releases now, not Bikeshed trunk.
